export default [
	{
		"name":"大熊猫",
		"key":"daxiongmao",
		"icon":"../../static/animal_icon/daxiongmao.jpg"
	},
	{
		"name":"北极熊",
		"key":"beijixiong",
		"icon":"../../static/animal_icon/beijixiong.jpg"
	},
	{
		"name":"东北虎",
		"key":"dongbeihu",
		"icon":"../../static/animal_icon/dongbeihu.jpg"
	},
	{
		"name":"蓝鲸",
		"key":"lanjing",
		"icon":"../../static/animal_icon/lanjing.jpg"
	},
	{
		"name":"雪豹",
		"key":"xuebao",
		"icon":"../../static/animal_icon/xuebao.jpg"
	},
	{
		"name":"扬子鳄",
		"key":"yangzie",
		"icon":"../../static/animal_icon/yangzie.jpg"
	},
	{
		"name":"红豆杉",
		"key":"hongdoushan",
		"icon":"../../static/animal_icon/hongdoushan.jpg"
	},
	{
		"name":"银杏",
		"key":"yinxing",
		"icon":"../../static/animal_icon/yinxing.jpg"
	}
]